# Generated by Django 5.0.2 on 2025-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
